/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz.altas;

import entidades.Tutorados;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import metodos.tutoradoMetodos;
/**
 *
 * @author rudy
 */
public class TutoradoAlta extends javax.swing.JInternalFrame {

    /**
     * Creates new form TutoradoAlta
     */
     tutoradoMetodos tutoradometodos = new tutoradoMetodos();
    public TutoradoAlta() {
        initComponents();
        cargarComboTutores();
        this.setSize(new Dimension(800, 400));
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = (screenSize.width - this.getWidth()) / 2;
        int alto = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(ancho, alto);
    }
    private void cargarComboTutores() {
        
        List<tutorComboBox> tutores = tutoradometodos.obtenerTutores();

        tutorCbx.removeAllItems(); // Limpia por si acaso

        /*for (tutorComboBox tutor : tutores) {
            tutorCbx.addItem(tutor); // Agrega los objetos
        }*/
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreTutorado = new javax.swing.JTextField();
        apellidoPaternoTutorado = new javax.swing.JTextField();
        apellidoMaternoTutorado = new javax.swing.JTextField();
        Matricula = new javax.swing.JTextField();
        telefonoTutorado = new javax.swing.JTextField();
        telefonoEmergenciaTutorado = new javax.swing.JTextField();
        domicilioTutorado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        afistxt = new javax.swing.JTextField();
        carreraCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tutorCbx = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setText("Apellido Paterno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setText("Apellido Materno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setText("Matricula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setText("Carrera");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel7.setText("Contacto de emergencia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel8.setText("Domicilio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        nombreTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTutoradoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreTutorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 105, 37));
        getContentPane().add(apellidoPaternoTutorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 105, -1));

        apellidoMaternoTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMaternoTutoradoActionPerformed(evt);
            }
        });
        getContentPane().add(apellidoMaternoTutorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 105, -1));
        getContentPane().add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 105, -1));
        getContentPane().add(telefonoTutorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 99, -1));

        telefonoEmergenciaTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoEmergenciaTutoradoActionPerformed(evt);
            }
        });
        getContentPane().add(telefonoEmergenciaTutorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 105, -1));
        getContentPane().add(domicilioTutorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 105, -1));

        jButton1.setText("Dar de alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 126, 49));

        jLabel9.setText("Afis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));
        getContentPane().add(afistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 105, -1));

        carreraCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "isc", "idm", "itcc", " " }));
        getContentPane().add(carreraCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 90, -1));

        jLabel10.setText("Tutor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        getContentPane().add(tutorCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTutoradoActionPerformed

    private void apellidoMaternoTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMaternoTutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoMaternoTutoradoActionPerformed

    private void telefonoEmergenciaTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoEmergenciaTutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEmergenciaTutoradoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
  
Object item = tutorCbx.getSelectedItem();
if (item == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un tutor.");
    return;
}
// Hacemos el cast (convertir) al tipo de dato de tu clase auxiliar
tutorComboBox tutorSeleccionado = (tutorComboBox) item; 

// 2. Recolectar datos de los TextFields
int tutorId = tutorSeleccionado.getId();
String nombre = nombreTutorado.getText();
String aPaterno = apellidoPaternoTutorado.getText();
String aMaterno = apellidoMaternoTutorado.getText();
String matricula = Matricula.getText();
String carrera = (String) carreraCombo.getSelectedItem(); 
String status = "Activo"; 
String telefono = telefonoTutorado.getText();
String telEmergencia = telefonoEmergenciaTutorado.getText();
String domicilio = domicilioTutorado.getText();

// --- AFIS ---
int afis = 0;
try {
    afis = Integer.parseInt(afistxt.getText()); 
} catch (NumberFormatException e) {
    afis = 0; 
}

// --- FECHA DE INSCRIPCIÓN (Faltaba esto) ---
// Obtenemos la fecha de hoy para guardarla
String fechaInscripcion = java.time.LocalDate.now().toString(); 

// 3. Validaciones básicas
if(nombre.isEmpty() || matricula.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Nombre y Matrícula son obligatorios.");
    return;
}

// 4. Guardar en BD
// Instanciamos el DAO si no lo tienes instanciado arriba
// TutoradoDAO tutoradoMetodos = new TutoradoDAO(); 

boolean exito = tutoradometodos.crearTutorado(
    tutorId, 
    nombre, 
    aPaterno, 
    aMaterno, 
    matricula, 
    carrera, 
    status, 
    telefono, 
    telEmergencia, 
    domicilio,
    afis,              // <--- El parámetro 11
    fechaInscripcion   // <--- EL PARÁMETRO 12 QUE FALTABA
);

    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tutorado registrado correctamente.");
        //limpiarFormulario(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar (revise matrícula duplicada).");
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField afistxt;
    private javax.swing.JTextField apellidoMaternoTutorado;
    private javax.swing.JTextField apellidoPaternoTutorado;
    private javax.swing.JComboBox<String> carreraCombo;
    private javax.swing.JTextField domicilioTutorado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreTutorado;
    private javax.swing.JTextField telefonoEmergenciaTutorado;
    private javax.swing.JTextField telefonoTutorado;
    private javax.swing.JComboBox<String> tutorCbx;
    // End of variables declaration//GEN-END:variables
}
